<a href="https://colab.research.google.com/github/MohammedShahad7/MY_Portfolio-/blob/main/Creating_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
sensor_ids = np.arange(200, 221, 4)

print("Task 1: Sensor IDs")
print(sensor_ids)
print("Shape:", sensor_ids.shape)

Task 1: Sensor IDs
[200 204 208 212 216 220]
Shape: (6,)


In [ ]:
daily_reading=np.zeros((6,4))

print("Task 2: Daily Readings")
print(daily_reading)
print("Shape:", daily_reading.shape)

Task 2: Daily Readings
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (6, 4)


In [ ]:
experiment_setuo=np.ones((3,6,4))

print("Task 3: Experiment Setup")
print(experiment_setuo)
print("Shape:", experiment_setuo.shape)

Task 3: Experiment Setup
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Shape: (3, 6, 4)


In [ ]:
colibration_valu=np.linspace(0,1,5)

print("Task 4: Calibration Values")
print(colibration_valu)
print("Shape:", colibration_valu.shape)

Task 4: Calibration Values
[0.   0.25 0.5  0.75 1.  ]
Shape: (5,)
