<a href="https://colab.research.google.com/github/MohammedShahad7/MY_Portfolio-/blob/main/Vectorized_Operations_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
energy_data=np.array([[12, 14, 13, 15, 16, 14],
 [10, 11, 12, 13, 14, 12],
 [20, 22, 21, 23, 24, 22],
 [ 8,  9, 10, 11, 12, 10],
 [15, 16, 17, 18, 19, 17]
                      ])

print("Enery Data:")
print(energy_data)
print("Shape",energy_data.shape)

Enery Data:
[[12 14 13 15 16 14]
 [10 11 12 13 14 12]
 [20 22 21 23 24 22]
 [ 8  9 10 11 12 10]
 [15 16 17 18 19 17]]
Shape (5, 6)


In [6]:
adjustment_data=energy_data*1.10

print("Adjustment Data:")
print(adjustment_data)

Adjustment Data:
[[13.2 15.4 14.3 16.5 17.6 15.4]
 [11.  12.1 13.2 14.3 15.4 13.2]
 [22.  24.2 23.1 25.3 26.4 24.2]
 [ 8.8  9.9 11.  12.1 13.2 11. ]
 [16.5 17.6 18.7 19.8 20.9 18.7]]


In [7]:
calibration_factors = [1.0, 0.98, 1.02, 1.01, 0.99, 1.03]

calibration_data=adjustment_data*calibration_factors

print("Calibration Data:")
print(calibration_data)


Calibration Data:
[[13.2   15.092 14.586 16.665 17.424 15.862]
 [11.    11.858 13.464 14.443 15.246 13.596]
 [22.    23.716 23.562 25.553 26.136 24.926]
 [ 8.8    9.702 11.22  12.221 13.068 11.33 ]
 [16.5   17.248 19.074 19.998 20.691 19.261]]


In [8]:
Average_energy_per_machine=np.mean(calibration_data,axis=1)

print("Average Energy Per Machine:")
print(Average_energy_per_machine)

Average Energy Per Machine:
[15.4715     13.26783333 24.3155     11.05683333 18.79533333]


In [9]:
Maximum_energy=np.max(calibration_data)

print("Maximum Energy:")
print(Maximum_energy)

Maximum Energy:
26.136000000000003
